source.. = tests/
output.. = bin/
bin.includes = META-INF/,\
               .

# Maven properties, see https://github.com/eclipse/tycho/wiki/Tycho-Pomless
tycho.pomless.parent = ../../
# Bundle name ends in ".tests" so Tycho's naming heuristic should infer this,
# but pin it explicitly to avoid surprises.
pom.model.packaging = eclipse-test-plugin
